language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  set rtp+=after
  runtime! cm_parser/*.vim
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! vader/*' > /dev/null
