language: vim

sudo: required
dist: trusty

os: 
  - linux
  - osx

install:
  - bash ./ci/travis_install.sh
  - export PATH="$HOME/vim/bin:$PATH"

before_script: |
  git clone --depth 1  https://github.com/junegunn/vader.vim.git

script:
  - bash ./ci/travis_script.sh vim
  - bash ./ci/travis_script.sh nvim
